### ISSUE TITLE
"Node is either not visible or not an HTMLElement"

### ISSUE THREAD

**Issue by JoanneR** [suchipi/line-sticker-downloader#4]
When I runned it I get this error

```× Node is either not visible or not an HTMLElement
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\puppeteer\lib\ExecutionContext.js:349:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ElementHandle.click (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\puppeteer\lib\ExecutionContext.js:401:20)
    at async scrapeStickerUrls (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\line-sticker-downloader\index.js:43:5)
    at async downloadStickers (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\line-sticker-downloader\index.js:79:18)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\puppeteer\lib\helper.js:144:27)
    at scrapeStickerUrls (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\line-sticker-downloader\index.js:43:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async downloadStickers (C:\Users\Kerosene\AppData\Local\npm-cache\_npx\b4c8a2c5f7da7de6\node_modules\line-sticker-downloader\index.js:79:18)```

**Comment by kushgo** [comment]
same problem man

**Comment by Wintar** [comment]
In the file ``index.js``:
Change line 43 from;
`await elementHandle.click();`
to;
`await page.evaluate((elementHandle) => { elementHandle.click(); }, elementHandle);`

**Comment by littlelapin** [comment]
> In the file `index.js`: Change line 43 from; `await elementHandle.click();` to; `await page.evaluate((elementHandle) => { elementHandle.click(); }, elementHandle);`

hey i tried this myself and am still getting the error unfortunately

**Comment by Wintar** [comment]
> hey i tried this myself and am still getting the error unfortunately

Hm, not sure why. My install method was to install directly via the command line. (I think I ran ``npm install line-sticker-downloader`` in my folder of choice.) Not sure if that install method would fix anything. You'd also have to re-edit that line though.

Also, I have little-to-no node experience; The solution I found was a miracle after some research of the error...

**Comment by suchipi** [comment]
this fix has been published in the latest version
